all: 
	echo pwd ls mv cmp cat
echo: echo.c 
	gcc -o echo echo.c
pwd: pwd.c
	gcc -o pwd pwd.c
ls: ls.c
	gcc -o ls ls.c
mv: mv.c
	gcc -o mv mv.c
sort: sort.c
	gcc -o cmp cmp.c
cat: cat.c
	gcc -o cat cat.c
clean:
	rm -f echo pwd ls mv cmp
